### ISSUE TITLE
Unable to find resource css, default.css 

### ISSUE THREAD

**Issue by MisoraRin** [javaEE-had-been-black/error-record#20]
没有样式
![image](https://user-images.githubusercontent.com/17513853/92130628-88906d80-ee37-11ea-9b1a-099b7b133697.png)

**Comment by MisoraRin** [comment]
含有css的resource文件夹要放在webapp下
![image](https://user-images.githubusercontent.com/17513853/92130905-dd33e880-ee37-11ea-8d4b-93f3e7f9eeeb.png)

**Comment by zh-hang** [comment]
个人原因导致的问题
